kind: golang.Generate
spec:
  versionPackagePath: internal/version
---
kind: golang.Build
spec:
  outputs:
    linux-amd64:
      GOOS: linux
      GOARCH: amd64
    linux-arm64:
      GOOS: linux
      GOARCH: arm64
---
kind: common.Image
name: image-image-factory
spec:
  baseImage: alpine:3.18
  additionalImages: []
  customCommands:
    - apk add --no-cache --update
        bash
        binutils-aarch64
        binutils-x86_64
        cpio
        dosfstools
        efibootmgr
        kmod
        mtools
        pigz
        qemu-img
        squashfs-tools
        tar
        util-linux
        xfsprogs
        xorriso
        xz
  copyFrom:
    - stage: ghcr.io/siderolabs/grub:v1.6.0-3-g617d342
      source: /
      destination: /
    - stage: ghcr.io/siderolabs/grub@sha256:9c17d29995e569a30ef7e35bfc5aedf9fee4de7f285787322c90dc807af08302 # amd64
      source: /usr/lib/grub
      destination: /usr/lib/grub
    - stage: ghcr.io/siderolabs/grub@sha256:29014cfe94f68d815e94b990a381bdc464b78fc989e775c748894ce359bcf3a5 # arm64
      source: /usr/lib/grub
      destination: /usr/lib/grub
    - stage: ghcr.io/siderolabs/installer:v1.6.0
      source: /usr/share/grub/unicode.pf2
      destination: /usr/share/grub/unicode.pf2
---
kind: auto.CustomSteps
spec:
  steps:
    - name: integration.test
      toplevel: true
    - name: integration
      toplevel: true
      inputs:
        - base
---
kind: custom.Step
name: integration.test
spec:
  docker:
    enabled: true
    stages:
      - name: integration-build
        description: builds the integration test binary
        from: base
        steps:
          - script:
              command: go test -c -covermode=atomic -coverpkg=./... -tags integration ./internal/integration
              cache:
                - /root/.cache/go-build
                - /go/pkg
      - name: integration.test
        description: copies out the integration test binary
        steps:
          - copy:
              from: integration-build
              src: /src/integration.test
              dst: /integration.test
  makefile:
    enabled: true
    phony: true
    script:
      - "@$(MAKE) local-$@ DEST=$(ARTIFACTS)"
---
kind: custom.Step
name: integration
spec:
  makefile:
    enabled: true
    phony: true
    depends:
      - integration.test
    variables:
      - name: RUN_TESTS
        defaultValue: TestIntegration
      - name: TEST_FLAGS
        defaultValue: ""
    script:
      - "@$(MAKE) image-image-factory PUSH=true"
      - docker pull $(REGISTRY)/$(USERNAME)/image-factory:$(TAG)
      - docker run --rm --net=host --privileged -v /dev:/dev -v $(PWD)/$(ARTIFACTS)/integration.test:/bin/integration.test:ro --entrypoint /bin/integration.test $(REGISTRY)/$(USERNAME)/image-factory:$(TAG) -test.v $(TEST_FLAGS) -test.run $(RUN_TESTS)
  ghaction:
    enabled: true
    environment:
      REGISTRY: registry.dev.siderolabs.io
      TEST_FLAGS: "-test.schematic-service-repository=registry.dev.siderolabs.io/image-factory/schematic -test.installer-external-repository=registry.dev.siderolabs.io/siderolabs -test.installer-internal-repository=registry.dev.siderolabs.io/siderolabs -test.cache-repository=registry.dev.siderolabs.io/image-factory/cache"
---
kind: common.Build
spec:
  ignoredPaths:
    - node_modules/
---
kind: service.CodeCov
spec:
  targetThreshold: 25 # the actual coverage is much higher and reported from the integration test
