# commit to be tagged for the new release
commit = "HEAD"

project_name = "image-factory"
github_repo = "siderolabs/image-factory"
match_deps = "^github.com/(siderolabs/[a-zA-Z0-9-]+)$"

previous = "v0.4.1"
# pre_release = true

# [notes]
